### ISSUE TITLE
schedule class generates error when run_daily fires an event

### ISSUE THREAD

**Issue by mf42** [hhaim/hass#20]
Hi,
thanks for this great project!
As a first step I tried to use the schedule class for a simple switch. 
So I implemented a class 

    import appdaemon.plugins.hass.hassapi as hass
    import datetime
    import schedule 
    class ScheduleTest(hass.Hass):

    def initialize(self):
        self.log("start scheduleTest {0}".format(str(self.args)));
        self.sch = schedule.Schedule(self,
                                     self.args['schedule'],
                                     self.on_schedule_event,None)
        self.sch.init()
        
    def on_schedule_event(self,kwargs):
        self.log("event occured" )

and initiated it as

    simple_schedule_test:
     module: simpleSwitch
     class: ScheduleTest
      schedule:
        - { mode: c, start: { t: "11:19:00", d: 7}, end: { t: "11:20:00", d: 7} }

So I'd expect a "event occurred" msg in my log file.

Whenever run_daily fires (in this case 11:20:00 on sun) an event I got the message (in error.log) 

> Unexpected error during exec_schedule() for App: simple_schedule_test
2020-09-06 11:20:00.169493 WARNING simple_schedule_test: Args: {'name': 'simple_schedule_test', 'id': '29f9b8d5fcec4692a7e336576f353119', 'callback': <bound method Schedule._cb_event of <Schedule with 1 rules> 
=================================

>  <Rule start=11:19:00, end=11:20:00, mode=c, sday=7, eday=7> 'timestamp': datetime.datetime(2020, 9, 7, 9, 20, tzinfo=<UTC>), 'interval': 86400, 'basetime': datetime.datetime(2020, 9, 7, 9, 20, tzinfo=<UTC>), 'repeat': True, 'offset': 0, 'type': None, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'interval': 86400, 'constrain_days': 'sat', 'rule': <Rule start=11:19:00, end=11:20:00, mode=c, sday=7, eday=7>, 'state': 'off'}}
> 2020-09-06 11:20:00.169958 WARNING simple_schedule_test: ------------------------------------------------------------
> 2020-09-06 11:20:00.170932 WARNING simple_schedule_test: Traceback (most recent call last):
>   File "/Users/fiedel/appdaemon/lib/python3.8/site-packages/appdaemon/scheduler.py", line 181, in exec_schedule
>     await self.AD.state.set_state(
>   File "/Users/fiedel/appdaemon/lib/python3.8/site-packages/appdaemon/state.py", line 472, in set_state
>     old_state = deepcopy(self.state[namespace][entity])
>   File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 146, in deepcopy
>     y = copier(x, memo)
> .............
> ..........
> 
> TypeError: cannot pickle '_thread.RLock' object

> 2020-09-06`` 11:20:00.171552 WARNING simple_schedule_test: ------------------------------------------------------------

> 2020-09-06 11:20:00.172243 WARNING simple_schedule_test: Scheduler entry has been deleted

> 2020-09-06 11:20:00.172565 WARNING simple_schedule_test: ------------------------------------------------------------

I'm running Appdaemon (Version 4.0.5) in a virtualenv with, as you can see, python 3.8.

Initializing the app works fine:

> 2020-09-06 11:18:59.594615 INFO AppDaemon: Found 1 total apps
2020-09-06 11:18:59.599411 INFO AppDaemon: Terminating simple_schedule_test
2020-09-06 11:18:59.600421 INFO AppDaemon: Initializing app simple_schedule_test using class ScheduleTest from module simpleSwitch
2020-09-06 11:18:59.602966 INFO simple_schedule_test: start scheduleTest {'module': 'simpleSwitch', 'class': 'ScheduleTest', 'schedule': [{'mode': 'c', 'start': {'t': '11:19:00', 'd': 7}, 'end': {'t': '11:20:00', 'd': 7}}]}
2020-09-06 11:18:59.605594 INFO simple_schedule_test: event occured
2020-09-06 11:19:00.161988 WARNING AppDaemon: Logged an error to .homeassistant/conf/logs/errors.log
2020-09-06 11:20:00.171914 WARNING AppDaemon: Logged an error to .homeassistant/conf/logs/errors.log

I'd love to integrate this app but to be honest I'm a little bit lost at this stage.

Thank you for tips, hints, comments 

Michael

**Comment by hhaim** [comment]
@mf42 you are using the wrong package. 

You should import this 
```import ada.schedule ```

**Comment by mf42** [comment]
Thank you for the quick reply!
Sorry for confusion; I should have mentioned that in my test-environment I took all the relevant .py - files in one directory. That's the reason for the missing ada.

But when using your original structure I've got the same issue.

    simple_sw_power:
     module: heat_app
     class: SimpleSwitch
       schedule:
          - { mode: a, start: { t: "12:58:00", d: 7}, end: { t: "12:59:00", d: 7} }
     switch:
        switch: light.flurlicht
        enable: input_boolean.schedule_flurlicht

Result:

> 2020-09-06 12:58:00.002247 WARNING simple_sw_power: ------------------------------------------------------------
2020-09-06 12:58:00.016005 WARNING simple_sw_power: Unexpected error during exec_schedule() for App: simple_sw_power
2020-09-06 12:58:00.016549 WARNING simple_sw_power: Args: {'name': 'simple_sw_power', 'id': 'c4b03012388d4c52b959154095ab3fa1', 'callback': <bound method Schedule._cb_event of <Schedule with 1 rules> 
=================================
<Rule start=12:58:00, end=12:59:00, mode=a, sday=7, eday=7>

>  'timestamp': datetime.datetime(2020, 9, 7, 10, 58, tzinfo=<UTC>), 'interval': 86400, 'basetime': datetime.datetime(2020, 9, 7, 10, 58, tzinfo=<UTC>), 'repeat': True, 'offset': 0, 'type': None, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'interval': 86400, 'constrain_days': 'sat', 'rule': <Rule start=12:58:00, end=12:59:00, mode=a, sday=7, eday=7>, 'state': 'on'}}

> 2020-09-06 12:58:00.016920 WARNING simple_sw_power: ------------------------------------------------------------

> 2020-09-06 12:58:00.203090 WARNING simple_sw_power: Traceback (most recent call last):
  File "/Users/fiedel/appdaemon/lib/python3.8/site-packages/appdaemon/scheduler.py", line 181, in exec_schedule
    await self.AD.state.set_state(
  File "/Users/fiedel/appdaemon/lib/python3.8/site-packages/appdaemon/state.py", line 472, in set_state
    old_state = deepcopy(self.state[namespace][entity])
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_thread.RLock' object

**Comment by hhaim** [comment]
@mf42 you are using the HASS scheduler (which is a diff object) if you don't know what you are doing keep the same dir layout

**Comment by mf42** [comment]
...as I mentioned before, I kept the same dir layout and still have the problem. It must have something to do with my config (run Appdaemon + HA on Mac). Anyway, cheers.

**Comment by hhaim** [comment]
@mf42 could you use version 4.0 of AppDaemon?
It might be related. I will try to install latest

**Comment by mf42** [comment]
I tried to reproduce the error; it seems that it occurs whenever I use "rule=rule" in run_daily. I'll keep you informed..

**Comment by hhaim** [comment]
Have you not said that it happened with my original code without any change?

**Comment by mf42** [comment]
Yes. To be clear: in your original code you use "rule=rule" ->  generates the error in my env
So, inspirited by the discussion on  https://github.com/AppDaemon/appdaemon/issues/462 I changed it to 
**rule = str(rule)** and the SimpleSwitch works fine now. Happy now, thanks for your help.
